name: Common Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Show Environment
        run: |
          echo "Environment: ${{ inputs.environment }}"
