name: Outputs Lab

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.generate.outputs.version }}

    steps:
      - name: Generate Version
        id: generate

        run: |
          echo "version=v1.0.0" >> $GITHUB_OUTPUT

      - run: echo "Version Created"
