name: Job Dependencies Lab

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Step
        run: |
          echo "Building Application"
          sleep 10

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Test Step
        run: |
          echo "Running Tests"
          sleep 10

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Step
        run: |
          echo "Deploying Application"
