name: If Condition Lab

on:
  workflow_dispatch:

jobs:
  condition-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: echo "This always runs"

      - name: Step 2
        if: true
        run: echo "Condition is True"

      - name: Step 3
        if: false
        run: echo "You should never see this"
